name: PHPStan

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2

    - name: Install composer
      uses: php-actions/composer@v6

    - name: Run PHPStan
      uses: php-actions/phpstan@v3
      with:
        configuration: phpstan.neon.dist
        memory_limit: 256M

